#<KvLang>
<Container>

    orientation:'vertical'
    
    MDToolbar:
        type: 'top'
        title: 'Countify'
        left_action_items: [["cart-plus", lambda x: x]]
        right_action_items: [["menu", lambda x: x]]


    MDBoxLayout:




    MDBottomAppBar:    
        MDToolbar:
            elevation: 0
            icon: 'cart-plus'
            type: 'bottom'
            mode: "free-center"

